// <auto-generated />
using System;
using BestStudentCafedra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BestStudentCafedra.Migrations.SubjectAreaDb
{
    [DbContext(typeof(SubjectAreaDbContext))]
    [Migration("20210228082636_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BestStudentCafedra.Models.AcademicGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("FormationYear")
                        .HasColumnType("int")
                        .HasColumnName("formation_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("SpecialtyId")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("specialty_id")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SpecialtyId" }, "specialty_id");

                    b.ToTable("academic_group");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<int>("SemesterDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("semester_discipline_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SemesterDisciplineId" }, "semester_discipline_id");

                    b.HasIndex(new[] { "TypeId" }, "type_id");

                    b.ToTable("activity");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ActivityProtection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_id");

                    b.Property<float>("Points")
                        .HasColumnType("float")
                        .HasColumnName("points");

                    b.Property<DateTime>("ProtectionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("protection_date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActivityId" }, "activity_id");

                    b.HasIndex(new[] { "StudentId" }, "student_id");

                    b.ToTable("activity_protection");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("activity_type");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("discipline");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .HasColumnType("varchar(7)")
                        .HasColumnName("class")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("event_description")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int?>("ResponsibleTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_teacher_id");

                    b.Property<int>("SchedulePlanId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_plan_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResponsibleTeacherId" }, "responsible_teacher_id");

                    b.HasIndex(new[] { "SchedulePlanId" }, "schedule_plan_id");

                    b.ToTable("event");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("GraduationWorkId")
                        .HasColumnType("int")
                        .HasColumnName("graduation_work_id");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("mark");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "event_id");

                    b.HasIndex(new[] { "GraduationWorkId" }, "graduation_work_id");

                    b.ToTable("event_log");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.EventTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int>("SequentialNumber")
                        .HasColumnType("int")
                        .HasColumnName("sequential_number");

                    b.HasKey("Id");

                    b.ToTable("event_template");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.GraduationWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchievedDate")
                        .HasColumnType("date")
                        .HasColumnName("archieved_date");

                    b.Property<int?>("Result")
                        .HasColumnType("int")
                        .HasColumnName("result");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("reviewer_id");

                    b.Property<int?>("ScientificAdviserId")
                        .HasColumnType("int")
                        .HasColumnName("scientific_adviser_id");

                    b.Property<int?>("StudentId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Theme")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("theme")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ReviewerId" }, "reviewer_id");

                    b.HasIndex(new[] { "ScientificAdviserId" }, "scientific_adviser_id");

                    b.HasIndex(new[] { "StudentId" }, "student_id")
                        .HasDatabaseName("student_id1");

                    b.ToTable("graduation_work");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.GroupDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DisciplineId" }, "discipline_id");

                    b.HasIndex(new[] { "GroupId" }, "group_id");

                    b.ToTable("group_disciplines");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ProposedTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("proposed_topic");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.RatingControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("completion_date");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<int>("SemesterDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("semester_discipline_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "SemesterDisciplineId" }, "group_id")
                        .HasDatabaseName("group_id1");

                    b.HasIndex(new[] { "SemesterDisciplineId" }, "semester_discipline_id")
                        .HasDatabaseName("semester_discipline_id1");

                    b.ToTable("rating_control");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.SchedulePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("approved_date");

                    b.Property<string>("ApprovingOfficerName")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("approving_officer_name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("LastChangedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_changed_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupId" }, "group_id")
                        .HasDatabaseName("group_id2");

                    b.ToTable("schedule_plan");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.SemesterDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasColumnType("enum('Exam','DifferentialCredit','Credit')")
                        .HasColumnName("control_type")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int>("Semester")
                        .HasColumnType("int")
                        .HasColumnName("semester");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DisciplineId" }, "discipline_id")
                        .HasDatabaseName("discipline_id1");

                    b.ToTable("semester_discipline");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Specialty", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(8)")
                        .HasColumnName("code")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("AcademicDegree")
                        .IsRequired()
                        .HasColumnType("enum('Undergraduate','Specialty','Magistracy','Postgraduate')")
                        .HasColumnName("academic_degree")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Code")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.ToTable("specialty");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Student", b =>
                {
                    b.Property<int>("GradebookNumber")
                        .HasColumnType("int")
                        .HasColumnName("gradebook_number");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("char(15)")
                        .HasColumnName("phone_number")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("GradebookNumber")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GroupId" }, "group_id")
                        .HasDatabaseName("group_id3");

                    b.ToTable("student");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.StudentRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<float>("Points")
                        .HasColumnType("float")
                        .HasColumnName("points");

                    b.Property<int>("RatingId")
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RatingId" }, "sr_rating_id");

                    b.HasIndex(new[] { "StudentId" }, "sr_student_id");

                    b.ToTable("student_rating");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("academic_degree")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("post")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("teacher");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.TeacherDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DisciplineId" }, "discipline_id")
                        .HasDatabaseName("discipline_id2");

                    b.HasIndex(new[] { "TeacherId" }, "teacher_id");

                    b.ToTable("teacher_disciplines");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.TeacherRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("creating_date");

                    b.Property<int>("GraduationWorkId")
                        .HasColumnType("int")
                        .HasColumnName("graduation_work_id");

                    b.Property<string>("Motivation")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("motivation")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reject_reason")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("enum('ADVISER','REVIEWER')")
                        .HasColumnName("request_type")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("response_date");

                    b.Property<string>("ResponsePersonName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("response_person_name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Status")
                        .HasColumnType("enum('APPROVED','REJECTED')")
                        .HasColumnName("status")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GraduationWorkId" }, "graduation_work_id")
                        .HasDatabaseName("graduation_work_id1");

                    b.HasIndex(new[] { "TeacherId" }, "teacher_id")
                        .HasDatabaseName("teacher_id1");

                    b.ToTable("teacher_request");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ThemeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CafedraResponse")
                        .HasColumnType("enum('APPROVED','REJECTED')")
                        .HasColumnName("cafedra_response")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("creating_date");

                    b.Property<int>("GraduationWorkId")
                        .HasColumnType("int")
                        .HasColumnName("graduation_work_id");

                    b.Property<string>("Motivation")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("motivation")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reject_reason")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("response_date");

                    b.Property<string>("ResponsePersonName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("response_person_name")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Status")
                        .HasColumnType("enum('APPROVED','REJECTED')")
                        .HasColumnName("status")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("TeacherResponse")
                        .HasColumnType("enum('APPROVED','REJECTED')")
                        .HasColumnName("teacher_response")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("theme")
                        .UseCollation("utf8mb4_0900_ai_ci")
                        .HasCharSet("utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GraduationWorkId" }, "graduation_work_id")
                        .HasDatabaseName("graduation_work_id2");

                    b.ToTable("theme_request");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.AcademicGroup", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Specialty", "Specialty")
                        .WithMany("AcademicGroups")
                        .HasForeignKey("SpecialtyId")
                        .HasConstraintName("academic_group_ibfk_1")
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Activity", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.SemesterDiscipline", "SemesterDiscipline")
                        .WithMany("Activities")
                        .HasForeignKey("SemesterDisciplineId")
                        .HasConstraintName("activity_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.ActivityType", "Type")
                        .WithMany("Activities")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("activity_ibfk_1");

                    b.Navigation("SemesterDiscipline");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ActivityProtection", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Activity", "Activity")
                        .WithMany("ActivityProtections")
                        .HasForeignKey("ActivityId")
                        .HasConstraintName("activity_protection_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.Student", "Student")
                        .WithMany("ActivityProtections")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("activity_protection_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Event", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Teacher", "ResponsibleTeacher")
                        .WithMany("Events")
                        .HasForeignKey("ResponsibleTeacherId")
                        .HasConstraintName("event_ibfk_2");

                    b.HasOne("BestStudentCafedra.Models.SchedulePlan", "SchedulePlan")
                        .WithMany("Events")
                        .HasForeignKey("SchedulePlanId")
                        .HasConstraintName("event_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponsibleTeacher");

                    b.Navigation("SchedulePlan");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.EventLog", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Event", "Event")
                        .WithMany("EventLogs")
                        .HasForeignKey("EventId")
                        .HasConstraintName("event_log_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.GraduationWork", "GraduationWork")
                        .WithMany("EventLogs")
                        .HasForeignKey("GraduationWorkId")
                        .HasConstraintName("event_log_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("GraduationWork");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.GraduationWork", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Teacher", "Reviewer")
                        .WithMany("GraduationWorksReview")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("graduation_works_ibfk_3")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BestStudentCafedra.Models.Teacher", "ScientificAdviser")
                        .WithMany("GraduationWorksAdvice")
                        .HasForeignKey("ScientificAdviserId")
                        .HasConstraintName("graduation_works_ibfk_2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BestStudentCafedra.Models.Student", "Student")
                        .WithMany("GraduationWorks")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("graduation_works_ibfk_1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("ScientificAdviser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.GroupDiscipline", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Discipline", "Discipline")
                        .WithMany("GroupDiscipline")
                        .HasForeignKey("DisciplineId")
                        .HasConstraintName("group_discipline_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.AcademicGroup", "AcademicGroup")
                        .WithMany("GroupDiscipline")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("group_discipline_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicGroup");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.RatingControl", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.AcademicGroup", "AcademicGroup")
                        .WithMany("RatingControls")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("rating_control_ibfk_3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.SemesterDiscipline", "SemesterDiscipline")
                        .WithMany("RatingControls")
                        .HasForeignKey("SemesterDisciplineId")
                        .HasConstraintName("rating_control_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicGroup");

                    b.Navigation("SemesterDiscipline");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.SchedulePlan", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.AcademicGroup", "Group")
                        .WithMany("SchedulePlans")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("schedule_plan_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.SemesterDiscipline", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Discipline", "Discipline")
                        .WithMany("SemesterDisciplines")
                        .HasForeignKey("DisciplineId")
                        .HasConstraintName("semester_discipline_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Student", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.AcademicGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("student_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.StudentRating", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.RatingControl", "RatingControl")
                        .WithMany("StudentRatings")
                        .HasForeignKey("RatingId")
                        .HasConstraintName("student_rating_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.Student", "Student")
                        .WithMany("StudentRatings")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("student_rating_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RatingControl");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.TeacherDiscipline", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.Discipline", "Discipline")
                        .WithMany("TeacherDisciplines")
                        .HasForeignKey("DisciplineId")
                        .HasConstraintName("teacher_discipline_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.Teacher", "Teacher")
                        .WithMany("TeacherDisciplines")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("teacher_discipline_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.TeacherRequest", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.GraduationWork", "GraduationWork")
                        .WithMany("TeacherRequests")
                        .HasForeignKey("GraduationWorkId")
                        .HasConstraintName("teacher_request_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestStudentCafedra.Models.Teacher", "Teacher")
                        .WithMany("TeacherRequests")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("teacher_request_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraduationWork");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ThemeRequest", b =>
                {
                    b.HasOne("BestStudentCafedra.Models.GraduationWork", "GraduationWork")
                        .WithMany("ThemeRequests")
                        .HasForeignKey("GraduationWorkId")
                        .HasConstraintName("theme_request_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraduationWork");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.AcademicGroup", b =>
                {
                    b.Navigation("GroupDiscipline");

                    b.Navigation("RatingControls");

                    b.Navigation("SchedulePlans");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Activity", b =>
                {
                    b.Navigation("ActivityProtections");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Discipline", b =>
                {
                    b.Navigation("GroupDiscipline");

                    b.Navigation("SemesterDisciplines");

                    b.Navigation("TeacherDisciplines");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Event", b =>
                {
                    b.Navigation("EventLogs");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.GraduationWork", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("TeacherRequests");

                    b.Navigation("ThemeRequests");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.RatingControl", b =>
                {
                    b.Navigation("StudentRatings");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.SchedulePlan", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.SemesterDiscipline", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("RatingControls");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Specialty", b =>
                {
                    b.Navigation("AcademicGroups");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Student", b =>
                {
                    b.Navigation("ActivityProtections");

                    b.Navigation("GraduationWorks");

                    b.Navigation("StudentRatings");
                });

            modelBuilder.Entity("BestStudentCafedra.Models.Teacher", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("GraduationWorksAdvice");

                    b.Navigation("GraduationWorksReview");

                    b.Navigation("TeacherDisciplines");

                    b.Navigation("TeacherRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
